#include "CursesController.h"
#include "CollisionHandler.h"
#include "CursesView.h"
#include "Actor.h"
#include "InputActions.h"
#include "Game.h"
#include "Scene.h"
#include "ActorBehavior.h"
#include "Bitmap.h"
// include header so everything can just use this
